version: '3.8'

services:
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    ports:
      - "4181:4180"
    command:
      - --http-address=0.0.0.0:4180
      - --provider=oidc
      - --provider-display-name="YOUR SSO"
      - --oidc-issuer-url=https://your-oidc.example.com
      - --client-id=your-client-id
      - --client-secret=${CLIENT_SECRET}
      - --cookie-secret=${COOKIE_SECRET}
      - --redirect-url=https://your-oidc2-proxy-and-service.example.com/oauth2/callback
      - --upstream=http://nginx:80
      - --email-domain=*
      - --errors-to-info-log

  nginx:
    image: nginx:latest
  netshoot:
    image: docker-hub-mirror.linecorp.com/nicolaka/netshoot
    command: sleep infinity
