version: '3.8'

services:
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    ports:
      - "4180:4180"
    command:
      - --http-address=0.0.0.0:4180
      - --provider=keycloak-oidc
      - --oidc-issuer-url=https://your-oidc.example.com
      - --client-id=vault
      - --client-secret=${CLIENT_SECRET}
      - --cookie-secret=${COOKIE_SECRET}
      - --redirect-url=https://your-oidc2-proxy-and-service.example.com/oauth2/callback
      - --upstream=http://nginx:80
      - --email-domain=*
      - --errors-to-info-log

  nginx:
    image: nginx:latest

